# Plugins
plugins:
- jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chris Hodgson

# Allow Future dated posts
future: true

# Show blog
show_blog: false

# Show Google analytics
show_google_analytics: true

# Collections
collections:
  projects:
    output: true

#paginate:         20
#paginate_path:    "/blog/page:num"

# see http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  startings: [html, head, body]
  profile: false
  blanklines: false
  ignore:
    envs: [local]
