# Plugins
plugins:
- jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chris Hodgson
#paginate:         20
#paginate_path:    "/blog/page:num"

# Allow Future dated posts
future: true

# Collections
collections:
  projects:
    output: true

# Custom vars
# google_analytics: UA-12262661-1

# see http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  startings: [html, head, body]
  profile: false
  blanklines: false
  ignore:
    envs: [local]
