# Plugins
plugins:
- jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chris Hodgson

# used by contact us (formspree), atom.xml and sitemap.xml
url: staging.jamiesmithestates.com

#paginate:         20
#paginate_path:    "/blog/page:num"

# Allow Future dated posts
future: true

# Show blog
show_blog: false

# Collections
collections:
  projects:
    output: true

# Custom vars
# google_analytics: UA-12262661-1

# see http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  startings: [html, head, body]
  profile: false
  blanklines: false
  ignore:
    envs: [local]
